# Generated by Django 6.0.6 on 2026-06-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.SmallIntegerField(choices=[(1, 'Nike'), (2, 'Adidas'), (3, 'Puma'), (4, 'Converse'), (5, 'Vans'), (6, 'New Balance')])),
                ('nome', models.CharField(max_length=100)),
                ('tamanho', models.SmallIntegerField(choices=[(34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42')])),
                ('categoria', models.SmallIntegerField(choices=[(1, 'Casual'), (2, 'Corrida'), (3, 'Basquete'), (4, 'Skate'), (5, 'Trilha'), (6, 'Treino')])),
                ('ano_lancamento', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='tenis/fotos')),
                ('ativo', models.BooleanField(verbose_name='Está ativo?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
