# Generated by Django 6.0.6 on 2026-06-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenis',
            options={'verbose_name': 'Tênis', 'verbose_name_plural': 'Tênis'},
        ),
        migrations.AlterField(
            model_name='tenis',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Está ativo?'),
        ),
    ]
