# Generated by Django 6.0.6 on 2026-06-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0002_alter_tenis_options_alter_tenis_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenis',
            name='ano_lancamento',
            field=models.IntegerField(verbose_name='Ano de Lançamento'),
        ),
    ]
