# Generated by Django 6.0.6 on 2026-06-15 22:59

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenis', '0004_tenis_preco_tenis_preco_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenis',
            name='preco',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=10, verbose_name='Preço'),
        ),
    ]
